### PR TITLE
Adjust the Rust link in the readme

### LINKED ISSUE #223: Link to Rust site goes to 404.
## Steps to reproduce

In the README.md, click the link on the word Rust in the opening line: This is an early-stage framework for implementing Azure Functions in Rust.

## Expected  behavior

The user is taken to the rust-lang.org homepage. 

## Actual behavior

The user is taken to a 404 page on the rust website.

## Solution

The site link should be changed from https://www.rust-lang.org/en-US/ to https://www.rust-lang.org as the former no longer resolves to the latter.

### PR DESCRIPTION
**Pull request by rtyler**
Fixes #223

### CODE REVIEW

**Comment by peterhuene** [comment]
@rtyler can you open a PR to add yourself to `.clabot` file in the repo root?  The bot will consider you signed at that point.  Thanks!

**Comment by peterhuene** [comment]
I'm changing the branch to `dev`.  I'm going to release 0.7.0 this weekend which will include merging dev to master.

**Comment by peterhuene** [comment]
Can you rebase this PR of dev too?

**Comment by rtyler** [comment]
@peterhuene what CLA am I agreeing here? :thinking:

**Comment by peterhuene** [comment]
Effectively that any contributions you make will be licensed under the [repo's licence](https://github.com/peterhuene/azure-functions-rs/blob/master/LICENSE) (i.e. the MIT license).

**Comment by peterhuene** [comment]
@cla-bot recheck.

**Comment by peterhuene** [comment]
@cla-bot check.

**Comment by peterhuene** [comment]
Oh well, it apparently always uses master.  I think there's a way to point it at a file in a particular branch that is just a JSON array.  I'll fix that later.

**Comment by peterhuene** [comment]
Thanks for fixing this @rtyler! :)

**Pull request merged**
