### PR TITLE
New website!

### PR DESCRIPTION
**Pull request by t-eckert**
[link](https://t-eckert.github.io/azure-functions-rs/)

@peterhuene, let me know what you think about this first pass at a new website. There's not much new data, just a walkthrough that pulls straight from the README, but I think the design is a good start. If you want to see something different or have specific improvements in mind, please share. I figure building this site is a good way to grok the codebase and will keep at it if it's helpful.

### CODE REVIEW

**Comment by peterhuene** [comment]
This is awesome, @t-eckert :) Thanks for the headstart on this.  I like the aesthetics.  How difficult do you think it will be to get the examples to show nicely formatted code blocks for Rust, like Rocket does on their website?

**Comment by t-eckert** [comment]
Not too difficult, this was a 2 hour hack-fest so there is still a ways to go.

**Comment by peterhuene** [comment]
We should probably make a logo using [Ferris](http://rustacean.net/) too :) Whatever would convey "Azure Functions" without reusing the logo (unless we reach out to the team to get permission, of course).

**Comment by t-eckert** [comment]
I was playing around with this that uses the same colors as the Functions logo: 
image

**Comment by t-eckert** [comment]
Or this 
image

**Comment by peterhuene** [comment]
So for the "getting started" sections, I think we should break it down by trigger, starting with `HttpRequest` since it is the most common probably.  We can copy the examples for now, but we should probably find some cool "real world" examples implemented in C# and port them to the Rust equivalent; even better if we could show the two side-by-side so those that are already using Azure Functions with C# can see what a port to Rust looks like.

Regarding this PR, would you like to do additional work or get this merged now so we have something in place?

**Comment by t-eckert** [comment]
I agree, let's scope out a "sprint" for this week. If you make a project board for the site, we can add items to it to get done this week.

As for this PR, I think it would be good to merge it as is, even with the issues as the current site is a stale branch and the issues will help push me to improve it.

**Pull request merged**
