### PR TITLE
Merge dev to master.

### PR DESCRIPTION
**Pull request by peterhuene**

### CODE REVIEW

**Comment by t-eckert** [comment]
Do you want me to approve this by starting/finishing a review. Everything here has been checked at least once, right?

**Comment by peterhuene** [comment]
Feel free, but merge from dev to master should always be clean (only done upon releases).

**Comment by t-eckert** [comment]
That was my thinking. I just saw the message of 1 approving review needed and didn't know if you were able to do the review if you started the merge.

**Comment by peterhuene** [comment]
PRs which don't really need review I just merge with my omnipotent admin privs 😄.

**Comment by t-eckert** [comment]
I thought we were an autonomous collective.

**Pull request merged**
