### PR TITLE
include signalr runtime must be installed

### PR DESCRIPTION
**Pull request by demoray**
## What is the goal of this pull request?

To update the docs to inform users they need to install the signalr extension.

## What does this pull request change?

the signalr example readme.

## What work remains to be done?

N/A

## Do you consider it adequately tested?

YES

## Notes

### CODE REVIEW

**Comment by peterhuene** [comment]
@cla-bot check

**Comment by peterhuene** [comment]
Hmm, the extension should [automatically be installed](https://github.com/peterhuene/azure-functions-rs/blob/master/azure-functions/src/registry.rs#L15-L16) when running an application that makes use of SignalR bindings.

Did you run into problems running the application?

**Comment by peterhuene** [comment]
@cla-bot check

**Comment by demoray** [comment]
> Did you run into problems running the application?

Yes.  I had to install them by hand, which lead me to making the PR

**Comment by peterhuene** [comment]
Weird, I wonder if it's because 1.1.0 is out.  I don't believe I ever explicitly installed the extension while developing the SignalR bindings.

Without the extension installed and after running `cargo func run -s /tmp/foo`, does `/tmp/foo` contain `**/*SignalR*.dll`?

**Pull request closed without merging**
